# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # proses jobs lint dockerfile untuk file backend
  lint-order-service-dockerfile:
    docker:
      - image: cimg/base:stable
    # steps dari setiap jobs, tidak dikomen karena sudah ada di name
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing Hadolint
          command: docker pull hadolint/hadolint
      - run:
          name: Linting BackEnd Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < ./order-service/Dockerfile
  # build docker file dan push ke ghcr
  build-app-order-service:
    docker:
      - image: cimg/base:stable
    # steps dari setiap jobs, tidak dikomen karena sudah ada di name
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: "docker build -t ghcr.io/icaksh/order-service:latest ./order-service/"
      - run:
          name: Login to ghcr.io
          command: echo $GITHUB_ACCESS_TOKEN | docker login ghcr.io -u icaksh --password-stdin
      - run:
          name: Pushing Image to ghcr.io
          command: docker push ghcr.io/icaksh/order-service:latest

  lint-shipping-service-dockerfile:
    docker:
      - image: cimg/base:stable
    # steps dari setiap jobs, tidak dikomen karena sudah ada di name
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing Hadolint
          command: docker pull hadolint/hadolint
      - run:
          name: Linting BackEnd Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < ./shipping-service/Dockerfile

  # build docker file dan push ke ghcr
  build-app-shipping-service:
    docker:
      - image: cimg/base:stable
    # steps dari setiap jobs, tidak dikomen karena sudah ada di name
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: "docker build -t ghcr.io/icaksh/shipping-service:latest ./shipping-service/"
      - run:
          name: Login to ghcr.io
          command: echo $GITHUB_ACCESS_TOKEN | docker login ghcr.io -u icaksh --password-stdin
      - run:
          name: Pushing Image to ghcr.io
          command: docker push ghcr.io/icaksh/shipping-service:latest

workflows:
  order-service-workflow:
    jobs:
      - lint-order-service-dockerfile
      - build-app-order-service:
          requires: 
            - lint-order-service-dockerfile
  shipping-service-workflow:
    jobs:
      - lint-shipping-service-dockerfile
      - build-app-shipping-service:
          requires: 
            - lint-shipping-service-dockerfile